name: hello world!

on:
  push:
    branches:
      - main

jobs:
  say_hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello!
        run: |
          echo "hello world!!!"
      - name: current date
        run: |
          date
      - name: list directory (long)
        run: |
          ls -l
