name: deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_ON_COMMIT: ${{ contains(github.event.head_commit.message, '#skip') }}

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install deps
        run: npm install
      - name: check style
        run: npm run eslint
      - name: build code
        run: npm run build
      - name: test code
        run: npm run test
  deploy_to_prod:
    needs: [quality_check]
    if: ${{ github.event_name == 'push' && env.SKIP_ON_COMMIT == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: trigger render deploy
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_KEY }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: [deploy_to_prod]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && env.SKIP_ON_COMMIT == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: v
